name: "build-test"

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:

  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://pnpm.io/continuous-integration
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: |
          pnpm install
          pnpm test

  test-basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          toolchains: '[{"jdkVersion": "$((steps.setupJava.outputs.version))", "jdkHome": "$((steps.setupJava.outputs.path))"}]'
      - run: |
          cat ~/.m2/toolchains.xml

  test-expanded:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          toolchains: '[{"jdkVersion": "1.8", "provides": {"vendor": "temurin"}, "jdkHome": "/java/8", "configuration": {"extra": "read all about it"}}]'
          outputFile: .m2/toolchains.xml
      - run: |
          cat .m2/toolchains.xml

  test-filepath:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          outputFile: custom.xml
      - run: |
          cat custom.xml

  test-env-filepath:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          outputFile: $GITHUB_WORKSPACE/custom.xml
      - run: |
          cat $GITHUB_WORKSPACE/custom.xml
